openapi: 3.0.0
info:
  title: "API E-Digital"
  description: |
   API de firmado para E-Digital
  version: v1.2
  contact:
    name: Carlos Garcia
    email: carlos.garcia@e-digital.cl
    url: www.e-digital.cl
  x-logo:
    url: 'https://e-digital.cl/wp-content/uploads/2016/11/logo_final_2_slogan_menor2.png'
    altText: E-Digital
servers:
  - url: https://e-digital.cl/api

paths:
  /auth:
    post:
      $ref: api/auth.yaml#/operation
  /users:
    post:
      $ref: api/users.create.yaml#/operation
    put:
      $ref: api/users.change.yaml#/operation
  /users/{userID}:
    get:
      $ref: api/users.info.yaml#/operation
  /users/{userID}/history:
    get:
      $ref: api/users.history.yaml#/operation
  /users/{userID}/documents:
    get:
      $ref: api/users.documents.yaml#/operation
  /users/{userID}/cetificates:
    get:
      $ref: api/users.certificates.list.yaml#/operation
    post:
      $ref: api/users.certificates.create.yaml#/operation
  /users/{userID}/cetificates/{certificateID}:
    get:
      $ref: api/users.certificates.info.yaml#/operation
    put:
      $ref: api/users.certificates.remove.yaml#/operation
    delete:
      $ref: api/users.certificates.revoke.yaml#/operation
  /document:
    post:
      $ref: api/document.create.yaml#/operation
  /document/{documentsID}:
    get:
      $ref: api/document.info.yaml#/operation
    put:
      $ref: api/document.change.yaml#/operation
    delete:
      $ref: api/document.remove.yaml#/operation
  /document/{documentsID}/logs:
    get:
      $ref: api/document.logs.yaml#/operation
  /organizations:
    get:
      $ref: api/organizations.list.yaml#/operation
  /organizations/{organizationID}:
    get:
      $ref: api/organizations.info.yaml#/operation
  /organizations/{organizationID}/templates:
    get:
      $ref: api/organizations.templates.list.yaml#/operation
    post:
      $ref: api/organizations.templates.create.yaml#/operation
  /organizations/{organizationID}/templates{templateID}:
    delete:
      $ref: api/organizations.templates.remove.yaml#/operation
    get:
      $ref: api/organizations.templates.yaml#/operation
    put:
      $ref: api/organizations.templates.change.yaml#/operation
  /organizations/{organitzationID}/users:
    get:
      $ref: api/organizations.users.list.yaml#/operation
  /organizations/{organitzationID}/users/{userID}:
    delete:
      $ref: api/organizations.users.remove.yaml#/operation
    post:
      $ref: api/organizations.users.invite.yaml#/operation
tags:
 - name: Security
   description: Mecanismos de seguridad
 - name: Users
   description: Conjunto de API's que permiten la administración de los usuarios.
 - name: Organization
   description: Conjunto de API's que permiten la administración de los organizaciones.
 - name: Documents
   description: Conjunto de API's que permiten la administración de los documentos.
