openapi: 3.0.0
info:
  title: "API PÚBLICA e-Digital"
  description: |
    API PÚBLICA de servicios e-Gestión :<br>
    Esta documentación está diseñana para catalogar sus servicios para integraciones RESTFUL.
  version: v1.2
  contact:
    name: Carlos Garcia
    email: carlos.garcia@e-digital.cl
    url: https://e-digital.global
  x-logo:
    url: 'https://e-digital.global/media/logo-edigital.png'
    altText: E-Digital
servers:
  - url: https://apipub.e-digital.global/api

paths:
  /auth:
    post:
      $ref: api/auth.yaml#/operation
  /users:
    post:
      $ref: api/users.create.yaml#/operation
  /users/{cod_user}:
    get:
      $ref: api/users.info.yaml#/operation
    put:
      $ref: api/users.change.yaml#/operation
  /users/{cod_user}/history:
    get:
      $ref: api/users.history.yaml#/operation
  /users/{cod_user}/documents:
    get:
      $ref: api/users.documents.yaml#/operation
  /users/{cod_user}/cetificates:
    # get:
    #   $ref: api/users.certificates.list.yaml#/operation
    post:
      $ref: api/users.certificates.create.yaml#/operation
    # put:
    #   $ref: api/users.certificates.load.yaml#/operation
  /users/{cod_user}/cetificates/{certificate_id}:
    get:
      $ref: api/users.certificates.info.yaml#/operation
    put:
      $ref: api/users.certificates.renovate.yaml#/operation
    delete:
      $ref: api/users.certificates.revoke.yaml#/operation
  /document:
    post:
      $ref: api/document.create.yaml#/operation
  /document/{document_hash}:
    get:
      $ref: api/document.info.yaml#/operation
    # put:
    #   $ref: api/document.change.yaml#/operation
    delete:
      $ref: api/document.remove.yaml#/operation
    post:
      $ref: api/document.firm.yaml#/operation
  /document/{document_hash}/logs:
    get:
      $ref: api/document.logs.yaml#/operation
  /organizations:
    get:
      $ref: api/organizations.list.yaml#/operation
  /organizations/{cod_organization}:
    get:
      $ref: api/organizations.info.yaml#/operation
  /organizations/{cod_organization}/templates:
    get:
      $ref: api/organizations.templates.list.yaml#/operation
    # post:
    #   $ref: api/organizations.templates.create.yaml#/operation
  /organizations/{cod_organization}/templates/{template_id}:
    # delete:
    #   $ref: api/organizations.templates.remove.yaml#/operation
    get:
      $ref: api/organizations.templates.yaml#/operation
    # put:
    #   $ref: api/organizations.templates.change.yaml#/operation
  /organizations/{cod_organization}/users:
    get:
      $ref: api/organizations.users.list.yaml#/operation
  /organizations/{cod_organization}/users/{cod_user}:
    delete:
      $ref: api/organizations.users.remove.yaml#/operation
    post:
      $ref: api/organizations.users.invite.yaml#/operation
tags:
  - name: Security
    description: Mecanismos de seguridad
  - name: Users
    description: Conjunto de API's que permiten la administración de los usuarios.
  - name: Organization
    description: Conjunto de API's que permiten la administración de las organizaciones.
  - name: Documents
    description: Conjunto de API's que permiten la administración de los documentos.
